[package]
name = "xml-struct-gen"
version = "0.0.1-alpha"
edition = "2024"
license = "MIT"
description = "Generates Rust structs for working in a type-safe way with some XML formats"
repository = "https://github.com/richardstephens/xml-struct-gen-rs"

[dependencies]
anyhow = "1.0.89"
bimap = "0.6.3"
clap = { version = "4.0", features = ["derive"] }
heck = "0.5"
indexmap = "2.12.0"
linked_hash_set = "0.1.5"
proc-macro2 = "1.0.87"
quote = "1.0.37"
xml-rs = "1.0.0"
